### ISSUE TITLE
Blender hangs if attempting to load a solitary .s3o file

### ISSUE THREAD

**Issue by maackey** [sanguinariojoe/blender_s3o_import#2]
**Steps to reproduce:**
1.) Download a s3o from https://github.com/ZeroK-RTS/Zero-K/tree/master/Objects3d
2.) In Blender import a Spring (.s3o) object
3.) Select the downloaded s3o file
4.) Blender immediately becomes unresponsive

**Output from terminal:**
```
Traceback (most recent call last):
  File "/home/chris/.config/blender/2.76/scripts/addons/s3o_import.py", line 432, in execute
    load_s3o_file(self.filepath, context)
  File "/home/chris/.config/blender/2.76/scripts/addons/s3o_import.py", line 380, in load_s3o_file
    while os.path.basename(rootdir).lower() != "objects3d":
KeyboardInterrupt
```

The root cause stems from the fact that it's expecting the file to be part of the game's folder structure.

Apparently it's attempting to load the model's texture? Which is perhaps another issue entirely, because when loading the same file from the game's source (as the plugin is expecting) -- the geometry loads fine but the texture is not applied properly.

**Comment by sanguinariojoe** [comment]
Fixed in 770373112bf6b3a29ad8aa137b52fa6e74f44acb

Now you can import the object from the game (then the game folders structure will be followed), or copy the object (and optionally its textures) in a folder and import it
