### ISSUE TITLE
Importing piece hiearching and generating bones from it

### ISSUE THREAD

**Issue by Beherith** [sanguinariojoe/blender_s3o_import#7]
Is it possible to also import piece hierarchy and generate bones from s3o to make it suitable for use with https://github.com/Anarchid/blender2lus ?

I would love to colab!

**Comment by sanguinariojoe** [comment]
I already though about that, but never addressed it, mainly because in spring:1944 we have a really different animation stuff, so blender2lus is not really helpful for me.

The eventual problem I see is that bones may mess up at the time of exporting the dae file for spring.

**Comment by Beherith** [comment]
To be honest, I'm fine with using the original s3o in spring, what I really want to use this for is creating animations outside of manually coding bos/lua (which tends to be quite difficult in the final result). 

Is there anything I can offer you in return for implementing this feature?

**Comment by Anarchid** [comment]
> The eventual problem I see is that bones may mess up at the time of exporting the dae file for spring.

Assimp imports Collada skeletons into Spring as Empty pieces, all in an useless shadow hierarchy of empty pieces.

They work perfectly, but are entirely useless since there's no way for them to affect meshes (which would require bone weight vertex attributes to also be processed).

**Comment by Beherith** [comment]
TY for the import script, I had to swap axes, to import into blender correctly. You can now auto-rig s3os and export .bos animations from blender!

https://github.com/Beherith/Skeletor_S3O
